version: "3"

services:
  users-db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "users-db"

  users-service:
    build: ./users
    image: users-image:latest
    ports:
      - "8000:8000"
    depends_on:
      - "users-db"
    command:
      [
        "./wait-for-it.sh",
        "users-db:5432",
        "--",
        "npm",
        "run",
        "start"
      ]
    environment:
      - PORT=8000
      - JWT_SECRET_KEY="C9nj2IOt5ocBwGjZ6JFsTQ6SKt/Vkq+McLdTXzvsr4+9m+zwgEwTs6puaJFhlypjsg/wsO0jyovKkXq2Kbydsx5jpMLYkXzRGtdFqOoPsz/fm9wcgY1CyWBigG1vhLrxgqADIJNEudGFXrjxndXijra9UuSUVTJrkwIfG0+PIcijOE30h46SKhaz44Wj3VFedch4eNQbU6zBx4T+tiBF80N0gG/rl01k0WMiy5a2SMT6HViTYtRqaSASSL8Lmp90M3D7ktgVN8pgBIw+EDBsGFPsc65FfppVvmEm4XR7UsLnzGk5pXIi12KXMdAarMtEfOV58yqqodCcqwwUiZUwUg=="
      - PGHOST=users-db
      - PGUSER=admin
      - PGDATABASE=users-db
      - PGPASSWORD=admin
      - PGPORT=5432

  api-gateway-service:
    build: ./api_gateway
    image: api-gateway-image:latest
    ports:
      - "3000:3000"
    depends_on:
      - "users-service"
    environment:
      - PORT=3000
      - USER_APP_HOST=users-service
      - USER_APP_PORT=8000
      - WALLET_APP_HOST=wallets-service
      - WALLET_APP_PORT=8001
      - RIDE_APP_HOST=rides-service
      - RIDE_APP_PORT=8002
